<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"特产管理",
                        "menuJump":"列表",
                        "tableName":"techan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"特产留言管理",
                        "menuJump":"列表",
                        "tableName":"techanLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"特产收藏管理",
                        "menuJump":"列表",
                        "tableName":"techanCollection"
                    }
                ],
                "menu":"特产管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"景点管理",
                        "menuJump":"列表",
                        "tableName":"jingdian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"景点收藏管理",
                        "menuJump":"列表",
                        "tableName":"jingdianCollection"
                    }
                ],
                "menu":"景点管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"酒店管理",
                        "menuJump":"列表",
                        "tableName":"jiudian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"酒店留言管理",
                        "menuJump":"列表",
                        "tableName":"jiudianLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"酒店收藏管理",
                        "menuJump":"列表",
                        "tableName":"jiudianCollection"
                    }
                ],
                "menu":"酒店管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"美食管理",
                        "menuJump":"列表",
                        "tableName":"meishi"
                    }
                ],
                "menu":"美食管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"酒店星级管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJiudian"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"路线类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryLuxian"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"特产类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryTechan"
			        }
			
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"新闻管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"新闻管理"
			}
			,
			{
			"child":[
				{
					"buttons":[
						"查看"
					],
					"menu":"已退款订单",
					"tableName":"yituikuandingdan"
				},
				{
					"buttons":[
						"查看"
					],
					"menu":"已完成订单",
					"tableName":"yiwanchengdingdan"
				},
				{
					"buttons":[
						"查看"
					],
					"menu":"已发货订单",
					"tableName":"yifahuodingdan"
				},
				{
					"buttons":[
						"查看"
					],
					"menu":"未支付订单",
					"tableName":"weizhifudingdan"
				},
				{
					"buttons":[
						"查看"
					],
					"menu":"已取消订单",
					"tableName":"yiquxiaodingdan"
				},
				{
					"buttons":[
						"查看",
						"修改"
					],
					"menu":"已支付订单",
					"tableName":"yizhifudingdan"
				}
			],
			"menu":"订单管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"特产管理",
	                    "menuJump":"列表",
	                    "tableName":"techan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"特产留言管理",
	                    "menuJump":"列表",
	                    "tableName":"techanLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"特产收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"techanCollection"
	                }
	            ],
	            "menu":"特产管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"景点管理",
	                    "menuJump":"列表",
	                    "tableName":"jingdian"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"景点收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"jingdianCollection"
	                }
	            ],
	            "menu":"景点管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"酒店管理",
	                    "menuJump":"列表",
	                    "tableName":"jiudian"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"酒店留言管理",
	                    "menuJump":"列表",
	                    "tableName":"jiudianLiuyan"
	                }
	                ,
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"酒店收藏管理",
	                    "menuJump":"列表",
	                    "tableName":"jiudianCollection"
	                }
	            ],
	            "menu":"酒店管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"美食管理",
	                    "menuJump":"列表",
	                    "tableName":"meishi"
	                }
	            ],
	            "menu":"美食管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"新闻管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"新闻管理"
			}
			,
			{
				"child":[
					{
						"buttons":[
							"查看",
							"修改"
						],
						"menu":"已发货订单",
						"tableName":"yifahuodingdan"
					},
					{
						"buttons":[
							"查看"
						],
						"menu":"未支付订单",
						"tableName":"weizhifudingdan"
					},
					{
						"buttons":[
							"查看"
						],
						"menu":"已取消订单",
						"tableName":"yiquxiaodingdan"
					},
					{
						"buttons":[
							"查看"
						],
						"menu":"已支付订单",
						"tableName":"yizhifudingdan"
					},
					{
						"buttons":[
							"查看"
						],
						"menu":"已退款订单",
						"tableName":"yituikuandingdan"
					},
					{
						"buttons":[
							"查看"
						],
						"menu":"已完成订单",
						"tableName":"yiwanchengdingdan"
					}
				],
				"menu":"订单管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
